project:
  type: book

book:
  title: "ADRF User Guide"
  author: "Jon Mills, Josh Edelmann, and Corey Sparks"
  date: last-modified
  date-format: "[Last Updated on] DD MMMM, YYYY"
  chapters:
    - index.md
    - 01-adrf-overview.md
    - 02-logging-in.md
    - 03-onboarding.md
    - 04-work.md
    - 05-access-data.md
    - 06-collaborate.md
    - 07-export.md
    - 08-dos-and-donts.md
    - 09-faq.md

  sidebar:
    style: docked
    search: true
    collapse-level: 1
    pinned: true

  search:
    location: sidebar
    type: textbox
    limit: 3

format:
  html:
    theme: journal
    backgroundcolor: "white"
    highlight-style: arrow
    embed-resources: false
    toc: true          # optional; this is the per-page “On this page” headings
    df-print: paged
    number-sections: false
    number-depth: 1

editor: visual